export const schematic = {
  DEFAULT_DASHED_ANIMATION_SPEED: 0,
  DEFAULT_GRID_SIZE: 10,
  DEFAULT_WIRE_COLOR: '#2C2F33',
  DEFAULT_NODE_RADIUS: 5,
  DEFAULT_PORT_COLOR: '#AAAAAA',
  DEFAULT_PORT_RADIUS: 5,
  DEFAULT_STROKE_WIDTH: 4,
  DEFAULT_VERTEX_RADIUS: 4,
  ERROR_COLOR: '#F47174',
  LABEL_POSITION_OFFSET: { x: 10, y: 0 },
  ROTATION_INCREMENT: 90,
  SELECTION_FPS: 30,
};
