export const schematic = {
  DEFAULT_DASHED_ANIMATION_SPEED: 0,
  DEFAULT_GRID_BREAK: 50,
  DEFAULT_GRID_SIZE: 10,
  DEFAULT_WIRE_COLOR: '#2c2f33',
  DEFAULT_NODE_RADIUS: 5,
  DEFAULT_PORT_RADIUS: 6,
  DEFAULT_STROKE_WIDTH: 4,
  LABEL_POSITION_OFFSET: { x: 10, y: 0 },
  ROTATION_INCREMENT: 90,
  SELECTION_FPS: 30,
};
